[project]
name = "mle-01-p1-team4"
version = "0.1.0"
description = "공공기관 사내 규정 기반 RAG 챗봇"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "chromadb",
    "langchain",
    "langchain-community",
    "langchain-openai",
    "langchain-text-splitters",
    "langchain-upstage>=0.7.7",
    "pypdf",
    "python-dotenv",
    "requests>=2.34.2",
    "streamlit",
]
