[project]
name = "mle-01-p1-team4"
version = "0.1.0"
description = "공공기관 사내 규정 기반 RAG 챗봇"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "chromadb",
    "langchain",
    "langchain-chroma>=1.1.0",
    "langchain-community",
    "langchain-huggingface>=1.2.2",
    "langchain-openai",
    "langchain-text-splitters",
    "langchain-upstage>=0.7.7",
    "matplotlib>=3.11.1",
    "pypdf",
    "python-dotenv",
    "requests>=2.34.2",
    "sentence-transformers>=5.7.0",
    "streamlit",
    "umap-learn>=0.5.12",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
